import type { AvailabilityParams, BookingListParams, CommissionReportParams } from "./types";

export const spaKeys = {
  all: ["spa"] as const,
  outlets: () => ["spa", "outlets"] as const,
  treatments: (active?: boolean) => ["spa", "treatments", { active: !!active }] as const,
  treatmentsAll: () => ["spa", "treatments"] as const,
  therapistsAll: () => ["spa", "therapists"] as const,
  therapists: (params: { branch_id?: string; active?: boolean }) => ["spa", "therapists", params] as const,
  customers: (q: string) => ["spa", "customers", q] as const,
  employees: (q: string) => ["spa", "employees", q] as const,
  assistsAll: () => ["spa", "assists"] as const,
  assists: (params: { branch_id?: string; from?: string; to?: string }) => ["spa", "assists", params] as const,
  outletPicsAll: () => ["spa", "outlet-pics"] as const,
  outletPics: (branchId?: string) => ["spa", "outlet-pics", branchId ?? ""] as const,
  bookingsAll: () => ["spa", "bookings"] as const,
  bookings: (params: BookingListParams) => ["spa", "bookings", "list", params] as const,
  booking: (id: string) => ["spa", "bookings", "detail", id] as const,
  availability: (params: AvailabilityParams) => ["spa", "availability", params] as const,
  boardAll: () => ["spa", "board"] as const,
  board: (branchId: string, date: string) => ["spa", "board", branchId, date] as const,
  commissionRules: () => ["spa", "commission-rules"] as const,
  commissionsAll: () => ["spa", "commissions"] as const,
  commissions: (params: CommissionReportParams) => ["spa", "commissions", params] as const,
  me: () => ["spa", "me"] as const,
  myAssignmentsAll: () => ["spa", "me", "assignments"] as const,
  myAssignments: (date: string) => ["spa", "me", "assignments", date] as const,
  myCommissions: (month: string) => ["spa", "me", "commissions", month] as const,
  publicOutlets: () => ["spa", "public", "outlets"] as const,
  publicTreatments: (branchId: string) => ["spa", "public", "treatments", branchId] as const,
};
